### ISSUE TITLE
발표 자료 추가 과정 개선

### ISSUE THREAD

**Issue by incleaf** [chocolate-factory/chocolatier-meetup#1]
발표 자료 추가하는 과정을 마스터에 직접 업로드하지 않고 브랜치 만들어서 PR 통해 마스터로 머지하는 방식으로 진행하는건 어떨까요?

오타 혹은 불명확한 내용에 코멘트 남겨서 글을 다듬으면 좋을 것 같습니다.

**Comment by Junu-Sinclair** [comment]
좋습니다.
불필요한 지저분함을 줄일 수 있을 것 같네요.

**Comment by yangroro** [comment]
리뷰어도 지정을 하면 좋을 것 같아요. 리뷰어 지정 없이는 아무도 안보는 PR이 생길 것 같네요.

**Comment by incleaf** [comment]
다들 복기하는 차원에서 해당 미팅 참여자 모두 다 리뷰어로 넣는건 어떨까여

**Comment by JungleKim** [comment]
전부 다 리뷰어로 놓고 마찬가지로 다음 발표전까지 Approve완료하기로 하면 될것같습니다.
리뷰를 위해 하루~이틀이상 빨리 자료를 올려줘야 겠네요.

**Comment by Junu-Sinclair** [comment]
발표한 주 금요일 까지는 업로드 하고 주말에 리뷰 하는 기간으로 잡는 정도로 하면 좋을 것 같습니다.

**Comment by incleaf** [comment]
그렇다면 앞으로 PR을 통해 마스터에 머지 하는 것으로 하고, 지금까지 올라온 자료들은 마스터 브랜치를 포스 푸시로 날린 후에 PR을 올리겠습니다.
