### ISSUE TITLE
자료 첨부 방식

### ISSUE THREAD

**Issue by yangroro** [chocolate-factory/chocolatier-meetup#2]
이번주에는 제가 예제 프로젝트를 미리 준비해왔습니다.  
https://github.com/chocolate-factory/docker-compose-example 에 프로젝트를 만들어놨는데 https://github.com/chocolate-factory/chocolatier-meetup/ 하위의 문서와 함께 둘지 현재처럼 별도 repository로 유지할지 결정했으면 합니다.

**Comment by incleaf** [comment]
저는 링크만 연결해두고 별도로 유지하는 것에 한 표입니다~

**Comment by Junu-Sinclair** [comment]
저도 별도 유지 한표입니다.
사이즈가 작으면 상관 없지만 추후에 사이즈가 큰 프로젝트 가 예제로 포함되는 등이 되면 예외상황이 필연적으로 발생할 것 같습니다.

**Comment by yangroro** [comment]
별다른 이견이 없는 것 같네요. 별도 유지 후 링크로 결정할게요. 대신 지속 가능성을 위해서 예제 프로젝트같은 경우엔 
가능하면 https://github.com/chocolate-factory 하위에 생성하는 걸로 하시죠.
